# Generated by Django 4.2 on 2023-04-24 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
