# Generated by Django 4.2 on 2023-04-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0002_image_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
