# Generated by Django 4.2 on 2023-04-24 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0003_rename_image_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
